insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
vinsert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mrs');

insert into COURSE_MATERIAL (url, course_id) values ('http://acquirethisname.com/ut/suscipit/a/feugiat/et.png', 1);
insert into COURSE_MATERIAL (url, course_id) values ('https://shutterfly.com/quis/augue/luctus.jsp', 2);
insert into COURSE_MATERIAL (url, course_id) values ('http://toplist.cz/sed/sagittis/nam/congue/risus.html', 3);
insert into COURSE_MATERIAL (url, course_id) values ('https://about.com/vestibulum/ante.jsp', 4);
insert into COURSE_MATERIAL (url, course_id) values ('http://mapy.cz/potenti/in/eleifend/quam.jpg', 5);
insert into COURSE_MATERIAL (url, course_id) values ('http://dell.com/convallis.js', 6);
insert into COURSE_MATERIAL (url, course_id) values ('http://wikispaces.com/in.jsp', 7);
insert into COURSE_MATERIAL (url, course_id) values ('http://archive.org/ut/mauris/eget/massa/tempor/convallis.aspx', 8);
insert into COURSE_MATERIAL (url, course_id) values ('https://dyndns.org/faucibus/orci/luctus.aspx', 9);
insert into COURSE_MATERIAL (url, course_id) values ('http://pcworld.com/vestibulum/ante/ipsum/primis.html', 10);
insert into COURSE_MATERIAL (url, course_id) values ('https://1und1.de/integer/non/velit/donec/diam/neque/vestibulum.json', 11);
insert into COURSE_MATERIAL (url, course_id) values ('http://mashable.com/erat/nulla/tempus/vivamus/in/felis.aspx', 12);
insert into COURSE_MATERIAL (url, course_id) values ('https://icq.com/consectetuer/adipiscing/elit/proin/interdum.jpg', 13);
insert into COURSE_MATERIAL (url, course_id) values ('http://php.net/quam/turpis.aspx', 14);
insert into COURSE_MATERIAL (url, course_id) values ('http://npr.org/lorem/id/ligula/suspendisse/ornare/consequat/lectus.png', 15);
insert into COURSE_MATERIAL (url, course_id) values ('http://google.de/aliquet/ultrices/erat.html', 16);
insert into COURSE_MATERIAL (url, course_id) values ('http://parallels.com/vestibulum.jpg', 17);
insert into COURSE_MATERIAL (url, course_id) values ('http://discovery.com/ut/at.js', 18);
insert into COURSE_MATERIAL (url, course_id) values ('http://upenn.edu/luctus/et/ultrices/posuere.js', 19);
insert into COURSE_MATERIAL (url, course_id) values ('https://spotify.com/tempus/sit/amet/sem/fusce/consequat/nulla.aspx', 20);
insert into COURSE_MATERIAL (url, course_id) values ('http://chron.com/nam/nulla.aspx', 21);
insert into COURSE_MATERIAL (url, course_id) values ('https://seattletimes.com/mauris/non/ligula.jsp', 22);
insert into COURSE_MATERIAL (url, course_id) values ('http://blogger.com/odio/in/hac/habitasse/platea/dictumst/maecenas.json', 23);
insert into COURSE_MATERIAL (url, course_id) values ('https://unesco.org/interdum/in/ante.jpg', 24);
insert into COURSE_MATERIAL (url, course_id) values ('https://nature.com/phasellus/sit/amet/erat/nulla/tempus.json', 25);
insert into COURSE_MATERIAL (url, course_id) values ('https://joomla.org/vel/lectus/in/quam/fringilla/rhoncus/mauris.png', 26);
insert into COURSE_MATERIAL (url, course_id) values ('http://illinois.edu/varius.jsp', 27);
insert into COURSE_MATERIAL (url, course_id) values ('https://blogspot.com/morbi/non/lectus/aliquam/sit/amet/diam.json', 28);
insert into COURSE_MATERIAL (url, course_id) values ('http://goo.ne.jp/nisi/nam/ultrices/libero/non/mattis/pulvinar.jpg', 29);
insert into COURSE_MATERIAL (url, course_id) values ('http://mapy.cz/velit/id/pretium/iaculis/diam/erat/fermentum.jsp', 30);

insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-31', 'Earvin', 'Phillot', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-28', 'Alfi', 'Daniellot', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-18', 'Kristofer', 'Paolini', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-20', 'Roseanne', 'Baines', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-21', 'Karoly', 'Cheetham', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-14', 'Lou', 'Redd', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-23', 'Ransom', 'Persent', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-25', 'Martica', 'Woan', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-11', 'Lucille', 'Hufton', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-15', 'Sari', 'Cardenoso', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-12', 'Maribelle', 'Packe', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-05', 'Amity', 'Ruggieri', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-09', 'Wayne', 'Tesauro', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-02', 'Linn', 'Yannoni', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-27', 'Marie-jeanne', 'Finkle', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-30', 'Kalle', 'Seneschal', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-01', 'Roseanna', 'Ferrari', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-04', 'Forbes', 'Pietrasik', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-04', 'Heidi', 'Veasey', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-05', 'Emelita', 'Wiltshier', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-10', 'Auria', 'Suttle', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-13', 'Jenine', 'Bunhill', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-13', 'Ardeen', 'Leneham', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-27', 'Marcel', 'Burde', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-12', 'Arny', 'Driscoll', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-14', 'Kerstin', 'Tofano', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-26', 'Fidelia', 'Ruddell', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-29', 'Costanza', 'Lorenzo', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-18', 'Thekla', 'Stabler', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-29', 'Torrey', 'Seiller', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-21', 'Stearne', 'Puckham', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-09', 'Reynold', 'Rudolf', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-15', 'Hillary', 'Onyon', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-11', 'Mitchell', 'MacPadene', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-17', 'Cynthie', 'Leftwich', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-21', 'Vail', 'Souter', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-21', 'Tammie', 'De Hooch', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-09', 'Anna-diane', 'Filler', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-25', 'Myrvyn', 'Flowers', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-17', 'Christi', 'Parkes', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-27', 'Theresina', 'Burchmore', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-16', 'Bernhard', 'Hartzogs', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-14', 'Baldwin', 'Clohissy', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-12', 'Bren', 'Awmack', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-07', 'Stormie', 'De Bell', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-12', 'Kirstin', 'Dael', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-23', 'Consolata', 'Lafayette', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-06', 'Denys', 'Taffurelli', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-09', 'Amery', 'Maes', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-03', 'Ilyse', 'Skedgell', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-23', 'Renaldo', 'Swanton', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-29', 'Hanna', 'Grishankov', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-29', 'Inez', 'Fomichkin', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-08', 'Norman', 'Nelhams', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-19', 'Shelton', 'Bovey', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-26', 'Jonathan', 'Skokoe', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-19', 'Juliet', 'Zettoi', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-08', 'Elfreda', 'Monsey', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-10', 'Godard', 'Kurton', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-29', 'Jacquelynn', 'Sharples', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-16', 'Eleen', 'Boays', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-26', 'Kalli', 'Dumini', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-18', 'Georgia', 'Debnam', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-18', 'Hersch', 'Willisch', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-16', 'Harald', 'Mattingly', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-11', 'Steward', 'Greally', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-09', 'Marlena', 'Hartfield', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-14', 'Lucais', 'Fitzharris', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-16', 'Debor', 'Greatrex', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-25', 'Shermy', 'Strange', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-18', 'Elana', 'Moakes', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-24', 'De', 'Belverstone', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-15', 'Adlai', 'Graalman', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-18', 'Manuel', 'Flanigan', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-26', 'Olive', 'Beverley', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-09', 'Mannie', 'Watsam', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-24', 'Timotheus', 'Chafney', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-14', 'Vanna', 'Hawler', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-14', 'Nina', 'Romanski', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-17', 'Merilee', 'Deackes', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-04', 'Margalit', 'Leadbeater', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-26', 'Jessey', 'Ackland', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-29', 'Joana', 'Armstead', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-28', 'Ambrose', 'Barsby', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-29', 'Noemi', 'Twitchett', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-14', 'Honey', 'Granleese', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-25', 'Filia', 'Tomblin', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-28', 'Bourke', 'Heifer', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-19', 'Napoleon', 'Chevin', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-14', 'Laurent', 'Snibson', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-28', 'Franky', 'Ragbourn', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-25', 'Daune', 'Gregson', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-27', 'Bertie', 'Reburn', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-07', 'Gael', 'Eborall', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-04', 'Kevyn', 'Creigan', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-27', 'Eloisa', 'Daughtry', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-28', 'Araldo', 'Housecroft', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-24', 'Kamilah', 'Rodolphe', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-05', 'Merry', 'Malyan', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-23', 'Avram', 'Rilston', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-26', 'Fons', 'Lesser', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-06', 'Gloriana', 'Danser', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-08', 'Patten', 'Rosenshine', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-13', 'Dasi', 'Keyworth', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-05', 'Torrey', 'McSherry', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-05', 'Christel', 'Issacoff', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-17', 'Adiana', 'Anster', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-20', 'Page', 'Benitez', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-10', 'Stacia', 'Shiell', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-20', 'Padraig', 'Mulliner', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-23', 'Brnaby', 'Keal', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-15', 'Letty', 'Scarf', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-16', 'Torr', 'Dries', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-07', 'Mikey', 'McNeill', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-26', 'Bibby', 'Sille', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-18', 'Yoshi', 'Beeston', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-07', 'Nolan', 'Petry', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-22', 'Flin', 'Hearnshaw', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-05', 'Alina', 'Haire', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-24', 'Sherwood', 'Cartmell', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-25', 'Katrine', 'Mealiffe', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-02', 'Thomasina', 'McCahey', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-10', 'Milton', 'Privost', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-20', 'Arvin', 'Saunder', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-19', 'Claude', 'Boole', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-16', 'Didi', 'Tumilson', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-08', 'Aile', 'Mycock', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-09', 'Hewe', 'Maccrae', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-24', 'Frazier', 'Clemmens', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-12', 'Freeman', 'Peverell', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-24', 'Klarika', 'Lowthorpe', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-16', 'Briano', 'Lathwood', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-02', 'Cullin', 'Cryer', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-24', 'Rubetta', 'Persence', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-01', 'Laughton', 'Cabrara', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-08', 'Louie', 'Cod', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-16', 'Lynelle', 'Server', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-26', 'Haydon', 'Djurisic', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-18', 'Domingo', 'Lawman', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-14', 'Briana', 'O''Kieran', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-10', 'Sauncho', 'Karpinski', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-30', 'Ted', 'Ambrogioni', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-12', 'Sidney', 'Barens', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-20', 'Husain', 'Hendren', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-16', 'Xylina', 'Tallquist', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-19', 'Tine', 'Wright', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-03', 'Felicia', 'Rizziello', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-16', 'Chery', 'Mayoral', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-16', 'Karolina', 'Exton', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-28', 'Wald', 'Pietz', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-12', 'Paulita', 'Pont', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-30', 'Allard', 'Sivewright', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-16', 'Florry', 'Gouch', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-30', 'Wendel', 'Jodkowski', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-07', 'Dacey', 'Bakster', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-12', 'Marillin', 'Sleany', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-18', 'West', 'Hexham', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-17', 'Ardine', 'Rowth', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-20', 'Camille', 'Pasmore', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-21', 'Karlan', 'Lemerle', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-05', 'Hendrik', 'Younie', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-16', 'Lib', 'Treasaden', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-03', 'Rozalin', 'Marzelle', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-02', 'Karlyn', 'Quinney', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-15', 'Amandie', 'Fink', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-06', 'Lowe', 'Luipold', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-29', 'Sephira', 'Dovydenas', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-21', 'Rex', 'Fitkin', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-24', 'Bertie', 'Dericut', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-04', 'Irvine', 'Nast', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-07', 'Calida', 'De Blasiis', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-29', 'Cletus', 'Van Velde', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-29', 'Kinny', 'Mullinger', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-02', 'Nicoli', 'Lannin', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-22', 'Fredric', 'Upchurch', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-02', 'Caprice', 'Jiracek', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-09', 'Debi', 'Doveston', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-10', 'Giustina', 'Kolczynski', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-12', 'Stafani', 'Pitkaithly', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-26', 'Abner', 'Shreeve', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-07', 'Scot', 'Elce', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-01', 'Winonah', 'Gather', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-10', 'Esdras', 'Stannas', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-19', 'Zonda', 'Hildred', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-03', 'Henryetta', 'Rushford', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-21', 'Georgeanna', 'MacKenny', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-17', 'Lindsey', 'Meekins', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-13', 'Dorolice', 'Cicculi', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-13', 'Ailina', 'Kiwitz', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-15', 'Alidia', 'Colliver', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-19', 'Jacquie', 'MacLaren', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-22', 'Rodney', 'Harkins', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-17', 'Celestyna', 'McPherson', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-04', 'Rocky', 'Ambroziak', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-27', 'Brande', 'McGilmartin', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-29', 'Bobbette', 'Algy', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-27', 'Toiboid', 'Pavelin', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-07', 'Mollee', 'Rosenbarg', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-26', 'Massimo', 'Mullany', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-20', 'Morgan', 'Plumm', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-22', 'Libbie', 'Ryman', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-23', 'Felipe', 'Garrish', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-20', 'Calley', 'Vedikhov', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-23', 'Caitrin', 'Benck', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-06', 'Caroline', 'Kesteven', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-10', 'Stefanie', 'Colliver', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-24', 'Shena', 'Boldison', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-19', 'Rafa', 'Bradborne', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-18', 'Corry', 'Blachford', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-15', 'Hortensia', 'Argente', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-05', 'Vina', 'Marchetti', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-14', 'Anson', 'Illyes', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-14', 'Suki', 'Bernardini', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-16', 'Monroe', 'Rajchert', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-24', 'Rodrick', 'Burgum', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-02', 'Ann-marie', 'Lente', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-05', 'Barbe', 'Frenchum', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-20', 'Smith', 'Tschiersch', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-09', 'Hannis', 'Danbury', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-04', 'Jeniece', 'Gaisford', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-09', 'Darrick', 'Hoult', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-28', 'Dionis', 'Freckelton', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-25', 'Torrance', 'Treversh', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-12', 'Kenna', 'Mussington', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-25', 'Car', 'Groveham', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-01', 'Dixie', 'Zavattari', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-03', 'Fayette', 'Staddon', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-13', 'Carolyn', 'Vina', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-27', 'Wilden', 'Mintram', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-12', 'Gerik', 'Pennicott', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-16', 'Town', 'Bill', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-09', 'Margaretha', 'Enrico', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-06', 'Collette', 'Edscer', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-27', 'Elyse', 'Erdis', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-04', 'Elliot', 'Sambals', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-07', 'Dyna', 'German', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-16', 'Morgen', 'Toor', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-28', 'Piotr', 'Spottswood', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-17', 'Tyne', 'Mabone', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-20', 'Zita', 'Ingall', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-18', 'Gradey', 'Heliot', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-15', 'Rosalia', 'Hyde-Chambers', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-10', 'Jacklyn', 'Gosnay', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-04', 'Haroun', 'Di Nisco', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-23', 'Sharity', 'Gidney', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-21', 'Herbert', 'Slyman', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-16', 'Aloysius', 'Landrick', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-04', 'Danice', 'Tullot', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-03', 'Kathryne', 'McPhilemy', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-12', 'Dale', 'Jendrassik', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-03', 'Josselyn', 'Weadick', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-21', 'Zonda', 'Bonnesen', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-20', 'Colene', 'Reddlesden', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-22', 'Erinna', 'Letch', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-28', 'Niall', 'Bartalot', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-20', 'Marvin', 'Naire', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-07', 'Kacey', 'Beetham', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-14', 'Frankie', 'Fitzsimon', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-12', 'Laureen', 'Linke', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-16', 'Lorin', 'Cockshott', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-05', 'Brena', 'Renard', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-14', 'Talbert', 'Mazzilli', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-10', 'Maurita', 'Heinel', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-12', 'Joli', 'Gianinotti', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-29', 'Cyrille', 'Crepin', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-17', 'Yasmeen', 'Goncaves', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-21', 'Martino', 'Somerville', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-02', 'Ruby', 'Gwinnett', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-28', 'Granville', 'Wolledge', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-06', 'Sarina', 'Palliser', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-24', 'Gustav', 'Gerry', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-18', 'Flory', 'Raleston', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-10', 'Arlena', 'Nisbith', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-04', 'Elna', 'Ockendon', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-19', 'Dee', 'Nise', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-10', 'Sisely', 'Garvie', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-01', 'Bria', 'Cockayne', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-09', 'Inglis', 'Laverick', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-09', 'May', 'Persehouse', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-10', 'Hubey', 'Muat', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-26', 'Yankee', 'Skeemor', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-03', 'Christie', 'Kenvin', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-05', 'Allissa', 'Threadkell', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-06', 'Pace', 'Hanaford', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-22', 'Forrest', 'Tremellan', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-08', 'Marvin', 'Patise', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-23', 'Richard', 'Micheu', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-21', 'Ida', 'Christofe', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-20', 'Allina', 'Schulter', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-14', 'Kathrine', 'Andrzej', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-28', 'Chaunce', 'Poynter', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-20', 'Jacquette', 'Gerrie', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-25', 'Roderick', 'Zarfati', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-06', 'Faydra', 'Mossman', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-06', 'Frederico', 'Bossel', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-01', 'Renie', 'Colleymore', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-16', 'Laetitia', 'Marfell', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-10', 'Alix', 'Kidder', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-19', 'Johnnie', 'Lamminam', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-04', 'Viki', 'Androli', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-09', 'Gaby', 'Lyptrit', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-29', 'Leticia', 'Awty', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-11', 'Carlita', 'Scholig', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-19', 'Thibaut', 'Jozaitis', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-25', 'Derk', 'Ruddock', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-11', 'Sissie', 'Hursthouse', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-22', 'Izzy', 'Plows', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-13', 'Noll', 'Pepperell', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-24', 'Devland', 'Soar', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-28', 'Berthe', 'Meek', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-19', 'Dallas', 'Uppett', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-02', 'Archer', 'Tythacott', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-07', 'Spike', 'Vossing', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-21', 'Marlee', 'Kmiec', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-04', 'Paxon', 'Bratley', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-16', 'Olav', 'Jerrom', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-11', 'Marji', 'Braim', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-06', 'Calli', 'Berryman', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-30', 'Delmar', 'Pedel', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-05', 'Mohandas', 'Nutbeam', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-10', 'Lisa', 'Daborne', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-08', 'Giffer', 'Crome', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-28', 'Fabe', 'Wimpenny', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-18', 'Juan', 'Bayldon', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-12', 'Nickie', 'Huortic', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-12', 'Miquela', 'Sebire', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-15', 'Courtnay', 'Gheeraert', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-21', 'Ingra', 'Zanetto', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-17', 'Kaylee', 'Grigoroni', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-30', 'Evered', 'Lebrun', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-20', 'Edgardo', 'Guess', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-07', 'Putnam', 'Cream', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-11', 'Will', 'Hampshire', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-22', 'Franciska', 'Guslon', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-21', 'Margaux', 'Ourry', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-12', 'Vinni', 'Hargreave', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-04', 'Cherye', 'Harmston', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-28', 'Kimball', 'Angier', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-27', 'Helenelizabeth', 'Parradine', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-19', 'Tallia', 'Pettitt', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-01', 'Sidney', 'Edmunds', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-10', 'Rowe', 'Eskriet', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-20', 'Chastity', 'Sharpin', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-21', 'Suzy', 'Dopson', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-17', 'Marie', 'McAviy', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-21', 'Belvia', 'Blenkiron', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-14', 'Frederico', 'Middlebrook', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-27', 'Katina', 'West', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-22', 'Collette', 'Cadany', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-27', 'Sammy', 'Zanini', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-12', 'Joaquin', 'Gilardoni', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-12', 'Nefen', 'Hoopper', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-15', 'Avrit', 'Beneix', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-01', 'Aeriel', 'Franzonello', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-30', 'Stirling', 'Leitche', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-20', 'Krishnah', 'Humbles', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-26', 'Selinda', 'Gayton', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-07', 'Mill', 'Moohan', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-23', 'Kinnie', 'Blaszczak', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-26', 'Halsey', 'Kardos', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-06', 'Xena', 'Earl', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-27', 'Livia', 'Gamett', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-07', 'Arlina', 'Hallsworth', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-15', 'Nehemiah', 'Lamy', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-16', 'Matthaeus', 'Kitcherside', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-17', 'Greer', 'Cleynaert', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-21', 'Dick', 'Bunning', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-30', 'Alikee', 'Adamson', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-20', 'Horten', 'Laguerre', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-15', 'Larine', 'Robardet', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-26', 'Samara', 'Quodling', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-19', 'Hans', 'Petrollo', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-07', 'Gerhardt', 'Stilliard', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-29', 'Nico', 'Malser', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-18', 'Marietta', 'Davinet', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-29', 'Gabi', 'Laborde', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-13', 'Taber', 'McIlheran', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-15', 'Cassi', 'Rentz', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-10', 'Corenda', 'Themann', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-18', 'Beatrice', 'Joret', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-24', 'Cathy', 'Grisewood', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-19', 'Abbie', 'Moulder', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-04', 'Devin', 'Bossel', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-11', 'Bridget', 'Godley', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-25', 'Carlos', 'Pick', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-21', 'Berny', 'Bernth', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-06', 'Elle', 'Malenfant', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-18', 'Jordana', 'Crichten', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-16', 'Liva', 'Caselli', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-19', 'Dedra', 'Collister', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-25', 'Barbabas', 'Ramsay', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-22', 'Mollie', 'Gothup', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-07', 'Hazel', 'Confort', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-16', 'Chris', 'McKissack', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-18', 'Rudie', 'Davidzon', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-11', 'Cecil', 'Shegog', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-18', 'Merrie', 'Galbreath', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-21', 'Harlene', 'Stentiford', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-15', 'Conrade', 'Esberger', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-05', 'Berrie', 'Clendennen', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-29', 'Brooks', 'Batstone', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-15', 'Bethena', 'Honnicott', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-18', 'Roxi', 'Lynds', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-01', 'Lynnet', 'Ainscow', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-08', 'Ludovico', 'Pickersgill', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-14', 'Elfreda', 'Pennoni', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-22', 'Raoul', 'Fance', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-02', 'Mikaela', 'Finey', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-26', 'Fields', 'Gubbins', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-21', 'Gabriellia', 'Huxtable', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-02', 'Audrie', 'Lenin', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-28', 'Jedediah', 'Culligan', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-02', 'Gottfried', 'Isacq', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-11', 'Laurice', 'Pettiford', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-06', 'Kora', 'Lines', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-12', 'Kiah', 'MacMeekan', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-28', 'Alexandros', 'Bernardeau', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-11-10', 'Paulette', 'Martell', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-12', 'Kipp', 'Padefield', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-21', 'Rhody', 'Chisnall', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-18', 'Nana', 'Shields', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-07', 'Stephanie', 'Worsalls', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-06', 'Aylmar', 'Leagas', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-14', 'Lyndsey', 'Doding', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-26', 'Rafe', 'Cake', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-04', 'Cullan', 'Mousby', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-27', 'Glory', 'Nottram', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-28', 'Joane', 'Heisham', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-06', 'Beverly', 'Loghan', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-02', 'Alvie', 'Rassmann', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-24', 'Claiborne', 'Stiell', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-13', 'Cort', 'Lemme', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-01', 'Dannel', 'Boam', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-08', 'Halette', 'O''Mara', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-10', 'Astrix', 'Cauley', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-06', 'Ebonee', 'Daunay', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-13', 'Coraline', 'Wimlett', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-10', 'Chere', 'Canada', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-14', 'Mariska', 'Thompson', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-28', 'Karola', 'De Roberto', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-23', 'Valeda', 'Visick', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-09', 'Cilka', 'Oley', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-27', 'Gardie', 'Yeskov', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-10', 'Stacie', 'Osgerby', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-16', 'Humfried', 'Donnersberg', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-16', 'Lucky', 'Rakes', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-03', 'Ardene', 'Edinburough', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-25', 'Bel', 'O''Corrigane', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-10', 'Hayyim', 'Cheney', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-12', 'Darnall', 'Cleave', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-26', 'Sheffie', 'Biggin', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-19', 'Dionne', 'Eyre', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-07-13', 'Dianemarie', 'Philot', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-25', 'Skippy', 'Okie', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-12', 'Brooks', 'Colter', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-03', 'Claiborn', 'Girdwood', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-21', 'Hobart', 'Lopez', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-06', 'Sasha', 'Beckinsall', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-04', 'Sonny', 'Wadham', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-10', 'Douglas', 'Gravy', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-28', 'Bard', 'O''Deoran', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-27', 'Jaymee', 'Megainey', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-04-07', 'Kasey', 'Brolan', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-26', 'Thorny', 'Butler', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-01', 'Percy', 'McJury', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-08', 'Sarena', 'Castiglione', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-30', 'Angie', 'Elderton', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-25', 'Tonya', 'FitzGilbert', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-16', 'Dwight', 'Dikels', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-04', 'Asher', 'Cordier', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-29', 'Leonanie', 'Rymell', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-03', 'Christan', 'Straneo', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-24', 'Nester', 'Solleme', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-20', 'Alfreda', 'Derrick', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-24', 'Karin', 'Davidek', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-13', 'Cecilia', 'Crankhorn', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-10', 'Judas', 'Dumper', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-01', 'Malanie', 'Sleightholm', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-16', 'Jessi', 'Francillo', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-03', 'Chloe', 'Domingues', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-02', 'Roxane', 'Fradgley', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-06', 'Lexie', 'Sillwood', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-11-24', 'Aland', 'Bedminster', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-11', 'Edmon', 'Studd', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-03-30', 'Riley', 'Dubique', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-15', 'Conny', 'Stiant', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-28', 'Benedick', 'Caltun', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-09-06', 'Chandra', 'Perrigo', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-10-13', 'Julienne', 'MacPhaden', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-07', 'Rene', 'Spyby', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-01', 'Fanchette', 'Derks', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-19', 'Humberto', 'Dudney', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-09', 'Jeremy', 'Heavy', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2021-12-03', 'Winne', 'Malley', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-06-07', 'Leroy', 'Ellif', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-01-01', 'Harriette', 'Penton', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-02-01', 'Julieta', 'Whapham', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-08', 'Vanna', 'Matthiesen', false);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-08-08', 'Issiah', 'Eakly', true);
insert into STUDENT (birth_date, first_name, last_name, wants_newsletter) values ('2022-05-31', 'Barde', 'Breakwell', true);

insert into COURSE_STUDENT (course_id, student_id) values (1, 1);
insert into COURSE_STUDENT (course_id, student_id) values (2, 2);
insert into COURSE_STUDENT (course_id, student_id) values (1, 2);
insert into COURSE_STUDENT (course_id, student_id) values (4, 4);
insert into COURSE_STUDENT (course_id, student_id) values (5, 5);
insert into COURSE_STUDENT (course_id, student_id) values (5, 6);
insert into COURSE_STUDENT (course_id, student_id) values (7, 7);
insert into COURSE_STUDENT (course_id, student_id) values (8, 8);
insert into COURSE_STUDENT (course_id, student_id) values (6, 9);
insert into COURSE_STUDENT (course_id, student_id) values (10, 10);
insert into COURSE_STUDENT (course_id, student_id) values (10, 13);
insert into COURSE_STUDENT (course_id, student_id) values (12, 12);
insert into COURSE_STUDENT (course_id, student_id) values (13, 13);
insert into COURSE_STUDENT (course_id, student_id) values (14, 14);
insert into COURSE_STUDENT (course_id, student_id) values (15, 15);
insert into COURSE_STUDENT (course_id, student_id) values (16, 16);
insert into COURSE_STUDENT (course_id, student_id) values (17, 17);
insert into COURSE_STUDENT (course_id, student_id) values (18, 18);
insert into COURSE_STUDENT (course_id, student_id) values (10, 19);
insert into COURSE_STUDENT (course_id, student_id) values (20, 20);
insert into COURSE_STUDENT (course_id, student_id) values (21, 21);
insert into COURSE_STUDENT (course_id, student_id) values (22, 22);
insert into COURSE_STUDENT (course_id, student_id) values (23, 23);
insert into COURSE_STUDENT (course_id, student_id) values (14, 24);
insert into COURSE_STUDENT (course_id, student_id) values (25, 25);
insert into COURSE_STUDENT (course_id, student_id) values (26, 26);
insert into COURSE_STUDENT (course_id, student_id) values (27, 27);
insert into COURSE_STUDENT (course_id, student_id) values (14, 28);
insert into COURSE_STUDENT (course_id, student_id) values (29, 29);
insert into COURSE_STUDENT (course_id, student_id) values (30, 30);
insert into COURSE_STUDENT (course_id, student_id) values (31, 31);
insert into COURSE_STUDENT (course_id, student_id) values (32, 32);
insert into COURSE_STUDENT (course_id, student_id) values (14, 33);
insert into COURSE_STUDENT (course_id, student_id) values (34, 34);
insert into COURSE_STUDENT (course_id, student_id) values (35, 35);
insert into COURSE_STUDENT (course_id, student_id) values (36, 36);
insert into COURSE_STUDENT (course_id, student_id) values (37, 37);
insert into COURSE_STUDENT (course_id, student_id) values (38, 38);
insert into COURSE_STUDENT (course_id, student_id) values (39, 39);
insert into COURSE_STUDENT (course_id, student_id) values (40, 40);
insert into COURSE_STUDENT (course_id, student_id) values (41, 41);
insert into COURSE_STUDENT (course_id, student_id) values (42, 42);
insert into COURSE_STUDENT (course_id, student_id) values (43, 43);
insert into COURSE_STUDENT (course_id, student_id) values (44, 44);
insert into COURSE_STUDENT (course_id, student_id) values (45, 45);
insert into COURSE_STUDENT (course_id, student_id) values (46, 46);
insert into COURSE_STUDENT (course_id, student_id) values (47, 47);
insert into COURSE_STUDENT (course_id, student_id) values (48, 48);
insert into COURSE_STUDENT (course_id, student_id) values (49, 49);
insert into COURSE_STUDENT (course_id, student_id) values (50, 50);
insert into COURSE_STUDENT (course_id, student_id) values (51, 51);
insert into COURSE_STUDENT (course_id, student_id) values (52, 52);
insert into COURSE_STUDENT (course_id, student_id) values (53, 53);
insert into COURSE_STUDENT (course_id, student_id) values (24, 54);
insert into COURSE_STUDENT (course_id, student_id) values (55, 55);
insert into COURSE_STUDENT (course_id, student_id) values (56, 56);
insert into COURSE_STUDENT (course_id, student_id) values (57, 57);
insert into COURSE_STUDENT (course_id, student_id) values (58, 58);
insert into COURSE_STUDENT (course_id, student_id) values (24, 59);
insert into COURSE_STUDENT (course_id, student_id) values (60, 60);
insert into COURSE_STUDENT (course_id, student_id) values (61, 61);
insert into COURSE_STUDENT (course_id, student_id) values (62, 62);
insert into COURSE_STUDENT (course_id, student_id) values (63, 63);
insert into COURSE_STUDENT (course_id, student_id) values (64, 64);
insert into COURSE_STUDENT (course_id, student_id) values (65, 65);
insert into COURSE_STUDENT (course_id, student_id) values (66, 66);
insert into COURSE_STUDENT (course_id, student_id) values (67, 67);
insert into COURSE_STUDENT (course_id, student_id) values (68, 68);
insert into COURSE_STUDENT (course_id, student_id) values (69, 69);
insert into COURSE_STUDENT (course_id, student_id) values (70, 70);
insert into COURSE_STUDENT (course_id, student_id) values (71, 71);
insert into COURSE_STUDENT (course_id, student_id) values (72, 72);
insert into COURSE_STUDENT (course_id, student_id) values (73, 73);
insert into COURSE_STUDENT (course_id, student_id) values (74, 74);
insert into COURSE_STUDENT (course_id, student_id) values (75, 75);
insert into COURSE_STUDENT (course_id, student_id) values (76, 76);
insert into COURSE_STUDENT (course_id, student_id) values (77, 77);
insert into COURSE_STUDENT (course_id, student_id) values (78, 78);
insert into COURSE_STUDENT (course_id, student_id) values (79, 79);
insert into COURSE_STUDENT (course_id, student_id) values (80, 80);
insert into COURSE_STUDENT (course_id, student_id) values (81, 81);
insert into COURSE_STUDENT (course_id, student_id) values (82, 82);
insert into COURSE_STUDENT (course_id, student_id) values (83, 83);
insert into COURSE_STUDENT (course_id, student_id) values (84, 84);
insert into COURSE_STUDENT (course_id, student_id) values (85, 85);
insert into COURSE_STUDENT (course_id, student_id) values (86, 86);
insert into COURSE_STUDENT (course_id, student_id) values (87, 87);